# Generated by Django 5.0.2 on 2024-02-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
