# Generated by Django 5.0.2 on 2024-02-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_posttable_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postTable',
            new_name='Company',
        ),
    ]
