# Generated by Django 5.0.2 on 2024-02-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_company_city_company_country_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
